version: '3.3'

services:
  web:
    image: 'tfilonych/healthy-plate:dev'
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    volumes:
      - ./client:/app/client
      - ./config:/app/config
      - ./imageStore:/app/imageStore
      - ./render:/app/render
      - ./server:/app/server
      - ./bootstrap.js:/app/bootstrap.js
      - ./bootstrappedFiles.js:/app/bootstrappedFiles.js
      - ./index.jsx:/app/index.jsx
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev", "--watch" ]